
#DEFINE rtfTimesNewRoman 0
#DEFINE rtfCourierNew    1
#DEFINE rtfArial         2
#DEFINE rtfTahoma        3
#DEFINE rtfVerdana       4

#DEFINE rfgNil      0
#DEFINE rfgRoman    1    
#DEFINE rfgDecor    2    
#DEFINE rfgTech     3
#DEFINE rfgScript   4
#DEFINE rfgSwiss    5
#DEFINE rfgModern   6  

#DEFINE raLeft      1  
#DEFINE raRight     2 
#DEFINE raCenter    3   
#DEFINE raJustify   4
#DEFINE raKeep      5   


#DEFINE rbLeft      1
#DEFINE rbRight     2
#DEFINE rbTop       3
#DEFINE rbBottom    4   
#DEFINE rbAll       5 
#DEFINE rblSingle   6
#DEFINE rblThick    7
#DEFINE rblShadow   8
#DEFINE rblDot      9
#DEFINE rblThin    10 

#DEFINE rfsBold          "1"
#DEFINE rfsItalic        "2" 
#DEFINE rfsStrike        "3"  
#DEFINE rfsUnderline     "4"
#DEFINE rfsUnderword     "5"   
#DEFINE rfsUnderdot      "6" 
#DEFINE rfsUnderdouble   "7"
#DEFINE rfsSuperScript   "8"
#DEFINE rfsSubScript     "9"  
#DEFINE rfsDefault       "0"
#DEFINE rfsKeep          "A"

#DEFINE CODEPAGE_RUSSION    1049  && 1033
